---
- name: Use debian mirror
  template: 
    src: sources.list.ui 
    dest: /etc/apt/sources.list

- name: Upgrade repos
  apt: 
    update_cache: yes
    upgrade: yes

- name: Install common packages
  apt:
    name: '{{item}}'
    state: present
  with_items: '{{ common_packages }}'

- name: Use locales
  locale_gen: 
    name: '{{ debian.locale }}' 
    state: present
